export type MenuItem = {
  name: string;
  weight: string;
  price: number;
  desc: string;
  tags?: ("vegetarian")[];
};

export type MenuCategory = {
  id: string;
  label: string;
  tagline: string;
  items: MenuItem[];
};

export const menuData: MenuCategory[] = [
  {
    id: "gustul-trilogy",
    label: "Gustul Trilogy",
    tagline: "Cele mai iubite și reprezentative preparate ale casei.",
    items: [
      { name: "Pui Crispy Trilogy", weight: "350g", price: 42, desc: "Piept de pui, cartofi prăjiți, sos Rose Trilogy, ou, susan alb, fulgi de porumb, panko, salată" },
      { name: "Coaste Porc Trilogy", weight: "750g", price: 65, desc: "Coaste de porc, cartofi prăjiți, salată, sos sweet chilli, sare, piper negru, boia" },
      { name: "Salată Trilogy cu Pui", weight: "300g", price: 39, desc: "Piept de pui, salată iceberg, roșii cherry, ou, lipie, măsline" },
      { name: "Omletă Trilogy", weight: "250g", price: 30, desc: "Ou, roșii, bacon, brânză brie, ulei de floarea soarelui, unt, pătrunjel, sare" },
      { name: "Penne Trilogy al Forno", weight: "300g", price: 45, desc: "Penne, cremă de gătit, bacon, gorgonzola, ou, parmezan, sos pizza" },
      { name: "Pizza Trilogy", weight: "600g", price: 45, desc: "Blat Trilogy, mozzarella, sos pizza, cașcaval, roșii, șuncă praga, salam de porc, porumb, bacon, ardei, brânză dură" },
      { name: "Burger Trilogy", weight: "360g", price: 48, desc: "Antricot de vită, chiflă, sos Rose Trilogy, ceapă, bacon, roșii, brânză cheddar, salată iceberg, castraveți murați" },
      { name: "Paste Trilogy", weight: "300g", price: 44, desc: "Tagliatelle, cremă de gătit, bacon, parmezan, gorgonzola" },
      { name: "Bruschete Trilogy", weight: "300g", price: 32, desc: "Pâine prăjită, pastă jumări, telemea, ceapă roșie" },
      { name: "Clătite cu Gutui", weight: "300g", price: 32, desc: "Ou, lapte, dulceață de gutui, făină de grâu dur, zahăr, înghețată — produs de sezon" },
    ],
  },
  {
    id: "hituri-bucatarie",
    label: "Hituri de Bucătărie",
    tagline: "Bucate cu energie, texturi surprinzătoare și gust desăvârșit.",
    items: [
      { name: "Tigaie Picantă Pui", weight: "350g", price: 42, desc: "Piept de pui, zucchini, ardei, ceapă, vânătă, sos sweet chilli, sos de soia, ardei iute" },
      { name: "Burger de Pui", weight: "350g", price: 44, desc: "Șnitel de pui, cartofi prăjiți, salată iceberg, chiflă, sos Rose Trilogy, bacon, roșii, brânză cheddar, castraveți murați" },
      { name: "Șnitel Parmigiana", weight: "250g", price: 39, desc: "Șnitel de pui, mozzarella, sos roșii, ou, brânză dură" },
      { name: "Paste Supreme", weight: "300g", price: 49, desc: "Tagliatelle, cremă de gătit, bacon, parmezan, gorgonzola, ulei extravirgin cu aromă de trufe" },
      { name: "Cartofi Gratinați", weight: "200g", price: 22, desc: "Cartofi, lapte, mozzarella, ou, unt", tags: ["vegetarian"] },
      { name: "Salată Caesar", weight: "200g", price: 39, desc: "Salată iceberg, piept de pui, parmezan, maioneză, crutoane, suc de lămâie, anșoa, capere" },
    ],
  },
  {
    id: "gusturi-romanesti",
    label: "Gusturi Românești",
    tagline: "Rețete românești cu gustul de altădată, gătite cu suflet.",
    items: [
      { name: "Ciulama Ardelenească", weight: "350g", price: 43, desc: "Piept de pui, mămăligă, ciuperci, usturoi, cremă de gătit" },
      { name: "Ficăței în Sos", weight: "300g", price: 33, desc: "Ficat de pui, unt, sos brun spaniol, usturoi" },
      { name: "Escalop Ardelenesc", weight: "300g", price: 38, desc: "Cotlet de porc, cremă de gătit, ciuperci, usturoi" },
      { name: "Ceafă Haiducească", weight: "350g", price: 43, desc: "Ceafă de porc, făină de grâu dur, ciuperci, unt, sos brun spaniol, usturoi" },
      { name: "Ceafă la Cuptor cu Cartofi și Rozmarin", weight: "300g", price: 46, desc: "Ceafă de porc, cartofi wedges, rozmarin" },
      { name: "Șnitel de Porc", weight: "200g", price: 33, desc: "Cotlet de porc, făină de grâu dur, ou" },
      { name: "Mix Grill 1 Persoană", weight: "550g", price: 55, desc: "Cotlet de porc, ceafă de porc, piept de pui, cârnați afumați, cartofi prăjiți, kaizer" },
      { name: "Mix Grill 2 Persoane", weight: "1100g", price: 98, desc: "Cotlet de porc, ceafă de porc, piept de pui, cârnați afumați, cartofi prăjiți, kaizer" },
      { name: "Mămăligă în Straturi", weight: "300g", price: 35, desc: "Mămăligă, smântână, bacon, cârnați afumați la rece, telemea, unt" },
      { name: "Cașcaval Pane", weight: "250g", price: 37, desc: "Cașcaval, ou, pesmet, ulei de floarea soarelui", tags: ["vegetarian"] },
      { name: "Mămăligă cu Brânză și Smântână", weight: "250g", price: 25, desc: "Mămăligă, smântână, telemea vacă, unt", tags: ["vegetarian"] },
    ],
  },
  {
    id: "arome-foc",
    label: "Arome de Foc Trilogy",
    tagline: "Carne, pește și preparate calde gătite pe grătar, pe plită sau în tigaie.",
    items: [
      { name: "Piept de Pui la Grătar", weight: "200g", price: 29, desc: "Piept de pui, sare, piper negru" },
      { name: "Ceafă la Grătar", weight: "250g", price: 37, desc: "Ceafă de porc, ulei de floarea soarelui, piper negru" },
      { name: "Cotlet la Grătar", weight: "250g", price: 33, desc: "Cotlet de porc, ulei de floarea soarelui" },
      { name: "Mușchi Vită la Grătar", weight: "200g", price: 59, desc: "Mușchi de vită, unt, piper roșu" },
      { name: "Burger Suprem", weight: "380g", price: 50, desc: "Antricot de vită, cartofi prăjiți, chiflă, ciuperci, cremă de gătit, sos Rose Trilogy, ou prăjit, bacon, gorgonzola, brânză cheddar" },
      { name: "Bucket Picant & Crocant", weight: "350g", price: 42, desc: "Crispy din piept de pui cu fulgi de porumb, cartofi prăjiți, sos Rose Trilogy, chilli fulgi, boia" },
      { name: "Polo à la King", weight: "350g", price: 46, desc: "Piept de pui, cremă de gătit, broccoli, ciuperci, mozzarella, gorgonzola, usturoi, lipie" },
      { name: "Piept de Pui Suprem", weight: "300g", price: 47, desc: "Piept de pui, hribi, ulei extravirgin cu aromă de trufe, gorgonzola" },
      { name: "Piept de Pui Gorgonzola", weight: "300g", price: 39, desc: "Piept de pui, cremă de gătit, gorgonzola" },
      { name: "Șnitel Pui în Crustă", weight: "200g", price: 37, desc: "Piept de pui, cașcaval, ou" },
      { name: "Shaorma la Farfurie", weight: "450g", price: 39, desc: "Piept de pui, cartofi prăjiți, sos Rose Trilogy, castraveți murați, varză, lipie, roșii, salată verde" },
      { name: "Șnitel de Pui", weight: "200g", price: 32, desc: "Piept de pui, făină de grâu dur, ou" },
      { name: "Cotoletă a la Bolognese", weight: "350g", price: 44, desc: "Cotlet de porc, cremă de gătit, cașcaval, sos pizza, șuncă praga, ou, pesmet" },
      { name: "Tigaie Picantă Vită", weight: "350g", price: 62, desc: "Mușchi de vită, zucchini, ardei, ceapă, vânătă, sos de soia, sos sweet chilli, ardei iute" },
      { name: "Tochitură cu Mămăliguță", weight: "250g", price: 53, desc: "Carne de porc, bacon, mălai, brânză telemea, cârnați afumați, ou ochi, vin alb sec" },
      { name: "Pomana Porcului", weight: "250g", price: 53, desc: "Carne de porc, bacon, mălai, untură, vin alb sec, usturoi" },
      { name: "Ciolan cu Iahnie", weight: "900g", price: 64, desc: "Ciolan afumat cu os, fasole, ceapă roșie, ardei, sos de roșii, pastă de tomate, morcov" },
      { name: "Mușchi Suprem", weight: "300g", price: 69, desc: "Mușchi de vită, cremă de gătit, ulei extravirgin cu aromă de trufe, hribi, gorgonzola, piper verde" },
      { name: "Mușchi Vită în Sos de Piper Verde", weight: "300g", price: 69, desc: "Mușchi de vită, cremă de gătit, piper verde" },
      { name: "Mușchi în Sos Brun", weight: "250g", price: 69, desc: "Mușchi de vită, sos brun spaniol" },
      { name: "Mușchi Vită Gorgonzola", weight: "250g", price: 69, desc: "Mușchi de vită, smântână de gătit, gorgonzola" },
      { name: "Mușchi de Vită în Coniac", weight: "200g", price: 69, desc: "Mușchi de vită, unt, coniac, rozmarin, piper verde" },
      { name: "Șnitel Vienez de Vită", weight: "150g", price: 61, desc: "Mușchi de vită, ou, panko" },
      { name: "Somon Lemon", weight: "240g", price: 61, desc: "Somon, roșii cherry, usturoi" },
      { name: "Somon Grill", weight: "200g", price: 57, desc: "Somon, piper negru, sare" },
    ],
  },
  {
    id: "paste",
    label: "Paste",
    tagline: "Gusturi italiene pe care le-am adus mai aproape de pofta românească.",
    items: [
      { name: "Carbonara Sos Alb", weight: "300g", price: 43, desc: "Spaghetti, bacon, parmezan, ou, cremă de gătit" },
      { name: "Carbonara Clasice", weight: "300g", price: 43, desc: "Spaghetti, bacon, parmezan, ou, gălbenuș" },
      { name: "Penne al Forno Sos Alb", weight: "300g", price: 43, desc: "Penne rigate, șuncă praga, ciuperci, cremă de gătit, mozzarella, parmezan" },
      { name: "Penne al Forno", weight: "300g", price: 43, desc: "Penne rigate, ciuperci, șuncă praga, cremă de gătit, mozzarella, parmezan, sos roșii" },
      { name: "Paste Somon Fume", weight: "300g", price: 43, desc: "Spaghetti, file de somon afumat, cremă de gătit, zucchini, roșii cherry" },
      { name: "Penne Arabiata", weight: "300g", price: 33, desc: "Penne rigate, parmezan, ardei iute, usturoi, sos pizza", tags: ["vegetarian"] },
      { name: "Spaghetti Oglio Peperoni", weight: "300g", price: 33, desc: "Spaghetti, parmezan, ulei de măsline, ardei iute, usturoi, pătrunjel" },
      { name: "Paste Milanese", weight: "300g", price: 43, desc: "Spaghetti, bacon, parmezan, cremă de gătit, sos roșii" },
      { name: "Penne Formaggi", weight: "300g", price: 43, desc: "Penne rigate, brânză brie, gorgonzola, mozzarella, parmezan, cremă de gătit, cașcaval", tags: ["vegetarian"] },
      { name: "Penne Amatriciana", weight: "300g", price: 33, desc: "Penne rigate, sos pizza, bacon, ardei, parmezan" },
      { name: "Paste cu Broccoli și Piept de Pui", weight: "450g", price: 44, desc: "Penne, cremă de gătit, piept de pui, broccoli" },
    ],
  },
  {
    id: "salate-garnituri",
    label: "Salate & Garnituri",
    tagline: "Fresh sau calde — perfecte ca bază, acompaniament sau masă ușoară.",
    items: [
      { name: "Orez cu Legume", weight: "200g", price: 15, desc: "Orez, morcov, ceapă, ardei, unt, pătrunjel, turmeric", tags: ["vegetarian"] },
      { name: "Broccoli Sote", weight: "200g", price: 20, desc: "Broccoli, unt, piper negru, sare", tags: ["vegetarian"] },
      { name: "Ciuperci Gorgonzola", weight: "200g", price: 20, desc: "Ciuperci, ulei de floarea soarelui, gorgonzola, cremă de gătit" },
      { name: "Ciuperci Sote", weight: "200g", price: 15, desc: "Ciuperci, unt, usturoi" },
      { name: "Cartofi Aurii", weight: "300g", price: 20, desc: "Cartofi, ulei de floarea soarelui, sare" },
      { name: "Ciuperci în Panko", weight: "250g", price: 28, desc: "Ciuperci, ou, ulei de floarea soarelui, panko" },
      { name: "Mămăliga", weight: "200g", price: 15, desc: "Făină de mălai, apă, sare" },
      { name: "Cartofi Rântăliți", weight: "250g", price: 22, desc: "Cartofi, ceapă albă, ulei de floarea soarelui, boia" },
      { name: "Salată Bulgărească", weight: "300g", price: 35, desc: "Telemea vacă, șuncă praga, ou, roșii, castraveți proaspeți, măsline, ardei" },
      { name: "Salată Somon Fume", weight: "300g", price: 43, desc: "Salată iceberg, file de somon afumat, castraveți proaspeți, ceapă, suc de lămâie" },
      { name: "Salată Grecească", weight: "300g", price: 34, desc: "Brânză telemea, salată iceberg, roșii, castraveți, măsline, ceapă, ulei de măsline, oregano", tags: ["vegetarian"] },
      { name: "Salată Cobb", weight: "350g", price: 39, desc: "Piept de pui, salată iceberg, roșii, gorgonzola, bacon, ou, ulei de măsline" },
      { name: "Salată Tabbouleh", weight: "200g", price: 24, desc: "Năut, castraveți, roșii, suc de lămâie, ceapă, ardei, pătrunjel", tags: ["vegetarian"] },
      { name: "Salata Coleslaw", weight: "150g", price: 20, desc: "Varză albă, morcov, ceapă albă, maioneză, zeamă de lămâie" },
      { name: "Salata Bucătarului", weight: "250g", price: 20, desc: "Roșii cherry, mozzarella, telemea vacă, busuioc, oregano, ulei de măsline" },
      { name: "Salată Ardei Copți", weight: "200g", price: 15, desc: "Ardei capia copt și decojit" },
      { name: "Salata Asortată", weight: "200g", price: 15, desc: "Ardei, roșii, castraveți, ceapă" },
      { name: "Salată Verde", weight: "250g", price: 15, desc: "Salată iceberg, suc de lămâie" },
      { name: "Sfeclă Roșie", weight: "200g", price: 15, desc: "Sfeclă roșie" },
      { name: "Salată Varză Albă", weight: "200g", price: 12, desc: "Varză, morcov, oțet de mere / oțet de vin" },
      { name: "Salată Mărături Asortate", weight: "200g", price: 15, desc: "Sfeclă roșie, castraveți murați, ardei capia copt și decojit" },
      { name: "Cartofi Domnești", weight: "200g", price: 22, desc: "Cartofi, cașcaval, usturoi" },
      { name: "Cartofi Pai", weight: "200g", price: 12, desc: "Cartofi prăjiți, ulei de palmier" },
      { name: "Cartofi Haiducești", weight: "200g", price: 20, desc: "Cartofi, ceapă, bacon, ulei de floarea soarelui, boia dulce" },
      { name: "Cartofi Wedges", weight: "200g", price: 20, desc: "Cartofi prăjiți, ulei de palmier, rozmarin, boia dulce" },
      { name: "Legume la Grătar", weight: "250g", price: 22, desc: "Dovlecel, vânătă, roșii, ceapă, ardei, ardei iute", tags: ["vegetarian"] },
    ],
  },
  {
    id: "pizza",
    label: "Pizza",
    tagline: "Pizza coaptă pe vatră, pentru serile în care ai chef de ceva bun.",
    items: [
      { name: "Pizza Capricciosa", weight: "550g", price: 41, desc: "Mozzarella, sos pizza, roșii, salam de porc, șuncă praga, cașcaval, ciuperci mixte, ardei, măsline, sos pesto" },
      { name: "Pizza Carbonara", weight: "450g", price: 43, desc: "Mozzarella, bacon, ou, cremă de gătit" },
      { name: "Pizza Americană", weight: "550g", price: 41, desc: "Mozzarella, sos pizza, roșii, șuncă praga, cașcaval, cartofi prăjiți, bacon" },
      { name: "Pizza Formaggi", weight: "600g", price: 43, desc: "Mozzarella, sos pizza, cașcaval, brânză brie, brânză cheddar, brânză de burduf, gorgonzola" },
      { name: "Pizza Prosciutto", weight: "550g", price: 39, desc: "Șuncă praga, mozzarella, sos pizza, roșii, cașcaval, brânză dură" },
      { name: "Pizza Vegetariană", weight: "550g", price: 39, desc: "Mozzarella, sos pizza, zucchini, roșii, cașcaval, ciuperci, porumb, măsline, brânză dură", tags: ["vegetarian"] },
      { name: "Pizza Italian Devil", weight: "600g", price: 43, desc: "Mozzarella, sos pizza, salam chorizo picant, gorgonzola, brânză dură, ardei iute" },
      { name: "Focaccia Cașcaval", weight: "250g", price: 25, desc: "Mozzarella, făină de grâu, ulei de floarea soarelui" },
      { name: "Pizza Margherita", weight: "550g", price: 33, desc: "Mozzarella, sos pizza, cașcaval, brânză dură, busuioc" },
    ],
  },
  {
    id: "mic-dejun-brunch",
    label: "Mic Dejun & Brunch",
    tagline: "Mic dejun cu gust, pentru dimineți în care ai chef de ceva bun.",
    items: [
      { name: "Mic Dejun American", weight: "350g", price: 35, desc: "Antricot de vită, ou prăjit, cartofi prăjiți, castraveți murați, bacon, ceapă, cheddar" },
      { name: "Mic Dejun Englezesc", weight: "350g", price: 35, desc: "Fasole, telemea vacă, ou prăjit, roșii proaspete, bacon" },
      { name: "Omletă cu Șuncă și Cașcaval", weight: "250g", price: 25, desc: "Ou, roșii, șuncă praga, cașcaval" },
      { name: "Omletă Țărănească", weight: "230g", price: 25, desc: "Ou, roșii proaspete, bacon, telemea vacă, ceapă, ardei" },
      { name: "Ochiuri la Capac", weight: "200g", price: 25, desc: "Roșii, ou, cașcaval, șuncă praga" },
      { name: "Omletă Brânză și Mărar", weight: "220g", price: 25, desc: "Ou, roșii, telemea vacă, mărar" },
      { name: "Cotto Panini", weight: "250g", price: 27, desc: "Salată iceberg, mozzarella, șuncă praga, roșii, ulei de măsline, oregano" },
      { name: "Prosciutto Panini", weight: "250g", price: 27, desc: "Mozzarella, rucola, prosciutto crudo, roșii, parmezan, ulei de măsline" },
      { name: "Shakshuka", weight: "300g", price: 30, desc: "Ouă, roșii, ardei, ceapă, usturoi, chimen", tags: ["vegetarian"] },
      { name: "Spanac cu Ochiuri", weight: "300g", price: 22, desc: "Spanac, cremă de gătit, ou prăjit, usturoi" },
      { name: "Plăcinte de Cartofi", weight: "200g", price: 26, desc: "Cartofi, telemea vacă, ou, parmezan, făină de grâu" },
      { name: "Caprese", weight: "200g", price: 22, desc: "Mozzarella, roșii, ulei de măsline, busuioc, oregano", tags: ["vegetarian"] },
      { name: "Humus", weight: "260g", price: 25, desc: "Năut, pastă din semințe de susan, ulei de măsline, usturoi", tags: ["vegetarian"] },
      { name: "Humus cu Pui", weight: "260g", price: 30, desc: "Năut, piept de pui, pastă din semințe de susan, ulei de măsline, usturoi" },
      { name: "Humus cu Vită", weight: "260g", price: 35, desc: "Năut, mușchi de vită, pastă din semințe de susan, ulei de măsline, usturoi" },
      { name: "Humus cu Muguri de Pin", weight: "260g", price: 30, desc: "Năut, pastă din semințe de susan, muguri de pin, ulei de măsline", tags: ["vegetarian"] },
      { name: "Humus cu Usturoi Caramelizat", weight: "350g", price: 25, desc: "Năut, tahini, usturoi, ulei de măsline, zahăr" },
      { name: "Humus cu Ardei Copt", weight: "350g", price: 25, desc: "Năut, ardei copt, tahini, ulei de măsline, usturoi" },
      { name: "Carpaccio Somon", weight: "300g", price: 45, desc: "Somon afumat, rucola, lămâie, ulei de măsline" },
      { name: "Carpaccio de Vită", weight: "250g", price: 45, desc: "Mușchi de vită, suc de lămâie, rucola, brânză dură, ulei de măsline" },
      { name: "Vinete Umplute", weight: "200g", price: 30, desc: "Vânătă, mozzarella, roșii, dovlecel, ardei, ceapă, cașcaval" },
      { name: "Bruschete cu Roșii", weight: "300g", price: 30, desc: "Pâine prăjită, roșii, parmezan, busuioc, oregano, ulei de măsline, usturoi" },
      { name: "Bruschete Vită", weight: "300g", price: 55, desc: "Pâine prăjită, mușchi de vită, parmezan, sos tartar, salată iceberg" },
      { name: "Bruschete Mixte", weight: "300g", price: 45, desc: "Pâine prăjită, roșii, parmezan, file de somon afumat, prosciutto crudo, ulei de măsline, usturoi" },
    ],
  },
  {
    id: "deserturi",
    label: "Deserturi Trilogy",
    tagline: "Ceva dulce la final, pentru un răsfăț pe deplin meritat.",
    items: [
      { name: "Lava Cake", weight: "200g", price: 25, desc: "Înghețată de vanilie, lava cake cu ciocolată, ou, unt, făină de grâu dur" },
      { name: "Papanași cu Finetti", weight: "300g", price: 30, desc: "Finetti, brânză de vaci, făină de grâu dur, ou, zahăr vanilat" },
      { name: "Papanași cu Dulceață", weight: "300g", price: 33, desc: "Smântână, brânză de vaci, dulceață de afine, făină de grâu dur, ou, zahăr pudră" },
      { name: "Clătite cu Finetti", weight: "200g", price: 25, desc: "Ou, lapte, Finetti, făină de grâu dur, zahăr, topping ciocolată" },
      { name: "Clătite cu Finetti și Banane", weight: "250g", price: 26, desc: "Clătite, banane, Finetti, înghețată de vanilie, topping ciocolată" },
      { name: "Clătite cu Nucă și Miere", weight: "200g", price: 26, desc: "Clătite, miere, nuci" },
      { name: "Clătite cu Dulceață", weight: "200g", price: 26, desc: "Clătite, dulceață de afine" },
      { name: "Crepes Suzette", weight: "150g", price: 26, desc: "Clătite, suc de portocale, coniac, unt, zahăr, coajă de portocală" },
      { name: "Gelatto", weight: "200g", price: 18, desc: "Înghețată de vanilie" },
    ],
  },
  {
    id: "extra-toppings",
    label: "Extra & Toppings",
    tagline: "Sosuri, toppinguri, adaosuri și ecotaxe ambalaj.",
    items: [
      { name: "Brânză", weight: "120g", price: 6, desc: "" },
      { name: "Șuncă", weight: "60g", price: 6, desc: "" },
      { name: "Mozzarella", weight: "60g", price: 6, desc: "" },
      { name: "Rucola", weight: "60g", price: 6, desc: "" },
      { name: "Salam", weight: "60g", price: 6, desc: "" },
      { name: "Prosciutto", weight: "60g", price: 8, desc: "" },
      { name: "Porumb", weight: "60g", price: 6, desc: "" },
      { name: "Sos Extra", weight: "60g", price: 6, desc: "" },
      { name: "Ciuperci", weight: "60g", price: 6, desc: "" },
      { name: "Miere Plic", weight: "15g", price: 2, desc: "" },
      { name: "Sos Gorgonzola", weight: "60g", price: 10, desc: "" },
      { name: "Pâine", weight: "50g", price: 2, desc: "" },
      { name: "Ambalaj Mic", weight: "", price: 3, desc: "" },
      { name: "Ambalaj Mare", weight: "", price: 6, desc: "" },
    ],
  },
];
